name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck shfmt || true
      - name: Shellcheck
        run: shellcheck bin/flux || true
      - name: JSON validity
        run: |
          jq . templates/site-fullstack.template.json >/dev/null
          jq . templates/site-static.template.json >/dev/null
          jq . security/firewall.json >/dev/null
          jq . examples/sites/transfer-hub.json >/dev/null
          jq . examples/sites/nickduchatinier.json >/dev/null
      - name: Format (dry-run)
        run: shfmt -d bin/flux || true
